Repository FromDoppler/Doppler-UI-System, pull requests merged in 2021-08, with the labels that each got.

#581 List selection page
  assets/icons/check-grey.svg
  assets/img/arrow-right-graphic.svg
  assets/img/check-grey.svg
  assets/scss/core/_reset.scss
  assets/scss/templates/_list-selection.scss
  assets/templates/list-selection-page.html
  assets/templates/partials/_navigation.html
Labels: size/XL

#583 feat: add exclude list modal for contact policy
  assets/js/main.js
  assets/scss/templates/_list-selection.scss
  assets/templates/contact-policy.html
Labels: size/L

#585 feat: add modal without list and modal error
  assets/js/main.js
  assets/scss/templates/_list-selection.scss
  assets/templates/contact-policy.html
Labels: size/L

#588 fix: add figcaption for images
  assets/img/check-green.svg
  assets/img/icon-pcontacto.svg
  assets/scss/templates/_list-selection.scss
  assets/templates/partials/_navigation.html
  assets/templates/promotional-page.html
Labels: size/L

#590 fix: adjust information icon size
  assets/scss/modules/_tooltip.scss
  assets/scss/templates/_doppler-plus.scss
  assets/templates/plan-calculator.html
Labels: size/S

#591 DW-1020
  assets/scss/modules/_card.scss
  assets/templates/doppler-plus.html
Labels: size/M

#593 Dw-1004
  assets/scss/modules/_messages.scss
  assets/scss/templates/_doppler-plus.scss
  assets/templates/doppler-plus.html
Labels: size/M

#592 DW-1090
  assets/scss/templates/_doppler-plus.scss
  assets/templates/doppler-plus.html
Labels: size/M

#594 DW-1024
  assets/scss/templates/_doppler-plus.scss
Labels: size/XS

#596 DW-1025
  assets/templates/plan-calculator.html
Labels: size/XS

#597 fix: improvement in deploying plans and icon change
  assets/img/arrow-grey-down.svg
  assets/scss/templates/_doppler-plus.scss
Labels: size/S

#599 feat: add list element inside promo banner
  assets/scss/templates/_doppler-plus.scss
  assets/templates/doppler-plus.html
Labels: size/M

#601 DW-1109
  assets/img/mercado-pago.svg
  assets/scss/modules/_forms.scss
  assets/scss/templates/_credit-card-component.scss
  assets/scss/templates/_payment-process.scss
  assets/templates/payment-process.html
Labels: size/XXL

#603 DW-1003
  assets/scss/helpers/_colors.scss
  assets/scss/templates/_guidelines.scss
  assets/templates/colors-component.html
Labels: size/L

#607 fix: fix in flashcards
  assets/scss/modules/_messages.scss
Labels: size/M

#608 fix: build errors
  Dockerfile
  package.json
Labels: size/S

#609 feat: create pages to develop dashboard
  assets/scss/modules/_carousel.scss
  assets/scss/modules/_messages.scss
  assets/scss/templates/_dashboard.scss
  assets/scss/templates/_guidelines.scss
  assets/templates/carousel-component.html
  assets/templates/dashboard.html
  assets/templates/index.html
  assets/templates/partials/_navigation.html
Labels: size/L
