Repository FromDoppler/Doppler-UI-System, pull requests merged in 2021-09, with the labels that each got.

#610 DW-1126
  assets/scss/modules/_card.scss
  assets/scss/templates/_doppler-plus.scss
Labels: size/S

#612 DW-1036
  assets/scss/templates/_payment-process.scss
  assets/templates/payment-process.html
Labels: size/M

#616 DS-2626-carousel-creation
  assets/js/main.js
  assets/scss/helpers/_colors.scss
  assets/scss/modules/_carousel.scss
  assets/templates/carousel-component.html
Labels: size/L

#618 fix: fin in credit card and summary
  assets/scss/templates/_payment-process.scss
  assets/templates/payment-process.html
Labels: size/L

#619 feat: add payment methods
  assets/scss/templates/_payment-process.scss
  assets/templates/payment-process.html
Labels: size/L

#624 Add new checkout success layout
  assets/img/checkout-success.svg
  assets/scss/core/_typography.scss
  assets/scss/helpers/_colors.scss
  assets/scss/templates/_payment-process.scss
  assets/templates/checkout-success.html
  assets/templates/partials/_navigation.html
  assets/templates/payment-process.html
Labels: size/L

#629 Fix(.gitattributes): add font extensions as binary
  .gitattributes
Labels: size/XS

#625 DW-1166-dashboard-panel
  assets/fonts/HandOfSeanPro-webfont.eot
  assets/fonts/HandOfSeanPro-webfont.ttf
  assets/fonts/HandOfSeanPro-webfont.woff
  assets/fonts/HandOfSeanPro-webfont.woff2
  assets/img/dashboard-book-disabled.svg
  assets/img/dashboard-book.svg
  assets/img/dashboard-ctr-disabled.svg
  assets/img/dashboard-ctr.svg
  assets/img/dashboard-deliveries-disabled.svg
  assets/img/dashboard-deliveries-icon-title.svg
  assets/img/dashboard-deliveries.svg
  assets/img/dashboard-list-icon-title.svg
  assets/img/dashboard-open-rate-disabled.svg
  assets/img/dashboard-open-rate.svg
  assets/img/dashboard-subscribers-icon-title.svg
  assets/img/dashboard-user-new-disabled.svg
  assets/img/dashboard-user-new.svg
  assets/img/dashboard-user-removed-disabled.svg
  assets/img/dashboard-user-removed.svg
  assets/js/main.js
  assets/scss/templates/_dashboard.scss
  assets/templates/dashboard.html
Labels: size/XL

#631 First steps
  assets/img/icon-book.svg
  assets/img/icon-pennant.svg
  assets/img/number-1.svg
  assets/img/number-2.svg
  assets/img/number-3.svg
  assets/img/ok-icon.svg
  assets/img/step-ok.svg
  assets/img/step-warning.svg
  assets/scss/templates/_dashboard.scss
  assets/templates/dashboard.html
Labels: size/L
