Repository FromDoppler/Doppler-UI-System, pull requests merged in 2022-04, with the labels that each got.

#718 fix: add ribbon styles
  assets/scss/modules/_ribbons.scss
Labels: size/L

#721 Revert "fix(deps-dev): bump cpy-cli from 3.1.1 to 4.1.0"
  npm-shrinkwrap.json
  package-lock.json
  package.json
Labels: size/XS

#720 DE-523 add icons family
  assets/fonts/glyph-smooth.eot
  assets/fonts/glyph-smooth.svg
  assets/fonts/glyph-smooth.ttf
  assets/fonts/glyph-smooth.woff
  assets/scss/helpers/_icons-glyph-smooth.scss
  assets/scss/styles.scss
  assets/templates/icons-components.html
  assets/templates/partials/_navigation.html
Labels: size/XXL

#722 Update pull_request_template.md
  pull_request_template.md
Labels: size/S

#726 fix: fix in doppler responsive menu
  assets/scss/templates/_header.scss
  assets/templates/header-component.html
Labels: size/S

#728 fix: fix in top menu responsive
  assets/scss/templates/_header.scss
Labels: size/XS
